### ISSUE TITLE
could you show its working in a video

### ISSUE THREAD

**Issue by Praskand** [mwdchang/fountain-code#1]
could you show its working in a video

**Comment by mwdchang** [comment]
Thanks for the interest, but I have no plans to publish a video recording of it.  You can, however, just see it working in the live-version: https://mwdchang.github.io/fountain-code/

**Comment by Praskand** [comment]
thanks!🙂

> Thanks for the interest, but I have no plans to publish a video recording of it. You can, however, just see it working in the live-version: https://mwdchang.github.io/fountain-code/
